name: Setup SSH for EC2 instance

on:
  push:
    branches:
      - chizim-chinuru-node-w-1

jobs:
  setup-ssh:
    runs-on: ubuntu-latest
    env:
      EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      EC2_URL: ${{ secrets.EC2_URL }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
    steps:
    - name: Setup SSH for EC2
      uses: omarhosny206/setup-ssh-for-ec2@v1.0.0
      with:
          EC2_SSH_PRIVATE_KEY: $EC2_SSH_PRIVATE_KEY
          EC2_URL: $EC2_URL
    # then you can run commands/scripts directly on the EC2 instance e.g.:
    - name: Create a new file on the EC2 instance with "hello-world"
      run: |
        ssh -o StrictHostKeyChecking=no -i $EC2_USERNAME@$EC2_URL

            cat <<EOF > /home/ubuntu/script.sh
            #!/bin/bash
            sudo apt update
            sudo apt upgrade -y
            sudo apt install nodejs -y
            sudo apt install npm -y
            git clone https://github.com/scarabeo7/node-challenge-quote-server.git
            cd node-challenge-quote-server
            git checkout chizim-chinuru-node-w-1
            npm install
            npm start
            EOF
            bash /home/ubuntu/script.sh
