name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - chizim-chinuru-node-w-1

jobs:
  deploy:
    name: Deploy quote server config to EC2 on chizim-chinuru-node-w-1 branch push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server 1
        uses: actions/checkout@v2
        
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cat <<EOF > /home/ubuntu/script.sh
            #!/bin/bash
            sudo apt update
            sudo apt upgrade -y
            sudo apt install nodejs -y
            sudo apt install npm -y
            git clone https://github.com/scarabeo7/node-challenge-quote-server.git
            cd node-challenge-quote-server
            git checkout chizim-chinuru-node-w-1
            npm install
            npm start
            EOF
            bash /home/ubuntu/script.sh
